name: Deploy

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3

      - name: Install sfdx cli
        run: sudo npm install @salesforce/cli --global

      - name: Deploy using mdapi
        run: |
          echo -e ${{ secrets.SERVER_KEY }} > ./server.key
          cat ./server.key
          sfdx auth:jwt:grant -i ${{ secrets.CLIENT_ID }} -f ./server.key --username ${{ secrets.USERNAME }} -r https://login.salesforce.com
          sfdx force:source:convert -d mdapi_output_dir
          sfdx force:mdapi:deploy -d mdapi_output_dir/ -u ${{ secrets.USERNAME }} -l RunSpecifiedTests --runtests "${{ secrets.TEST_CLASSES }}" -w -1
