name: Deploy

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  echo-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Echo repository secrets
      run: |
        echo "Secret One: ${{ secrets.CLIENT_ID }}"
        echo "Secret Two: ${{ secrets.SERVER_KEY }}"
        echo "Secret Three: ${{ secrets.TEST_CLASSES }}"
        echo "Secret Four: ${{ secrets.USERNAME }}"
